apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-crds
      version: "=2025.5.5"
      sourceRef:
        kind: HelmRepository
        name: linkerd
  values:
    installGatewayAPI: true