apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
spec:
  interval: 5m
  dependsOn:
    - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-control-plane
      version: "=2025.5.5"
      sourceRef:
        kind: HelmRepository
        name: linkerd
  values:
    controlPlaneLogFormat: json
    controlPlaneTracing: true
    podMonitor:
      enabled: true
    networkValidator:
      logFormat: json
    identity:
      externalCA: true
      issuer:
        scheme: kubernetes.io/tls
    proxy:
      metrics:
        hostnameLabels: true
      logFormat: json
    proxyInit:
      logFormat: json
