apiVersion: v1
kind: Pod
metadata:
  name: default-client
  namespace: default
  labels:
    source: kubectl-apply
    app: default-client
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-metrics-hostname-labels: "true"
spec:
  containers:
  - name: http-client
    image: curlimages/curl
    command:
      - "sh"
      - "-c"
      - "while sleep 0.25; do curl -s -o /dev/null -w \"%{http_code}\\n\" \"http://web-svc.emojivoto\" ; done"
---
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  namespace: emojivoto
  name: web-http
spec:
  accessPolicy: all-unauthenticated
  podSelector:
    matchLabels:
      app: web-svc
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1alpha1
kind: HTTPLocalRateLimitPolicy
metadata:
  namespace: emojivoto
  name: web-http
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: web-http
  identity:
    requestsPerSecond: 2